### ISSUE TITLE
重启服务报错,提示找不到Swoole\Process文件

### ISSUE THREAD

**Issue by zhanyangqi** [mixstart/mixphp#43]
PHP Fatal error:  Uncaught Error: Class 'Swoole\Process' not found in /www/wwwroot/xxx.com/mixphp/vendor/mixstart/mixphp-framework/src/helpers/ProcessHelper.php:40
Stack trace:
#0 /www/wwwroot/xxx.com/mixphp/vendor/mixstart/mixphp-framework/src/helpers/ProcessHelper.php(31): mix\helpers\ProcessHelper::kill('17120', 0)
#1 /www/wwwroot/xxx.com/mixphp/vendor/mixstart/mixphp-framework/src/helpers/ProcessHelper.php(64): mix\helpers\ProcessHelper::isRunning('17120')
#2 /www/wwwroot/xxx.com/mixphp/apps/httpd/commands/ServiceCommand.php(66): mix\helpers\ProcessHelper::readPidFile('/var/run/mix-ht...')
#3 /www/wwwroot/xxx.com/mixphp/apps/httpd/commands/ServiceCommand.php(83): apps\httpd\commands\ServiceCommand->actionStop()
#4 /www/wwwroot/xxx.com/mixphp/vendor/mixstart/mixphp-framework/src/console/Application.php(82): apps\httpd\commands\ServiceCommand->actionRestart()
#5 /www/wwwroot/xxx.com/mixphp/vendor/mixstart/mixphp-framework/src/console/Application.php in /www/wwwroot/xxx.com/mixphp/vendor/mixstart/mixphp-framework/src/helpers/ProcessHelper.php on line 40

**Comment by zhanyangqi** [comment]
@onanying

**Comment by han8gui** [comment]
原因可以说下吗

**Comment by onanying** [comment]
@han8gui  Swoole 没装，就是当前环境变量的php，用户装了多个php
